default:
  image: ruby:3

build:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - bundle install
    - bundle exec rake build
  pages: true
  artifacts:
    paths:
      - public
